Changes to proxy command
From Arran's example, this change is necessary. Otherwise the second Copy loop is guaranteed to exit with:

	Error: write /dev/stdout: use of closed network connection