Make the initial Run API call wait for the connection to be ready
Over in the runner repo, the steps-integration integration tests are
failing withe following error:

        ERROR: Job failed (system failure): container exec on "fb713040a3f77c360ea1c8a7829c03c6a9f91cf3189952b03c9ae347df352e78" finished with: executing step request: running job request: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: io: read/write on closed pipe"

The error appears to be caused by sending the Run request before the
connection is actually ready. This CallOption waits for the connection
to be ready before sending the Run request.

See:
* https://grpc.io/docs/guides/wait-for-ready/
* https://pkg.go.dev/google.golang.org/grpc#WaitForReady